### ISSUE TITLE
Error while setting up with Olson files (missing file)

### ISSUE THREAD

**Issue by vedarthk** [mde/timezone-js#185]
I am getting following error while setting up with Olson data files:

```
root@d810c7612026:/tmp/tz-data# node src/node-preparse.js tz
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'tz/pacificnew'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at parse (/tmp/tz-data/src/node-preparse.js:41:25)
    at Object.<anonymous> (/tmp/tz-data/src/node-preparse.js:74:20)
    at Object.<anonymous> (/tmp/tz-data/src/node-preparse.js:76:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

`pacificnew` is not available in the latest tar file from ftp://ftp.iana.org/tz/tzdata-latest.tar.gz

**Comment by mde** [comment]
This library is fairly old, and this repo is here mostly for historical interest. If you'd like to submit a PR that fixes this issue however, I'd be happy to merge it. Thanks!
